import '~/styles/globals.css';

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "~/components/header/Header";
import Carousel from "~/components/carousel/Carousel";
import ActionMoviesSection from "~/components/genre/ActionMoviesSection";
import ComedyMoviesSection from "~/components/genre/ComedyMovieSection";
import { Drama } from "lucide-react";
import DramaMoviesSection from "~/components/genre/DramaMoviesSection";
import HorrorMoviesSection from "~/components/genre/HorrorMovieSection";
import SciFiMoviesSection from "~/components/genre/SciFiMoviesSection";
import Footer from "~/components/footer/Footer";

export const metadata: Metadata = {
  title: "Movie Library",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function MainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-black text-white">
        <TRPCReactProvider>
          {/* 🔹 Header */}
          <Header />

          {/* 🔹 Top Carousel */}
          <Carousel />

          {/* 🔹 Genre Sections */}
          <ActionMoviesSection />
          <ComedyMoviesSection />
          <DramaMoviesSection />
          <HorrorMoviesSection />
          <SciFiMoviesSection />

          {/* 🔹 Footer */}
          <Footer />
          {/* 🔹 Page Content */}
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
