import '~/styles/globals.css';
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Header from "~/components/header/Header";
import Footer from "~/components/footer/Footer";
import { WatchlistProvider } from '~/hooks/WatchlistContext';

export const metadata: Metadata = {
  title: "Movie Library",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function MainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-black text-white">
          <WatchlistProvider> 
          <Header /> 
          <main>{children}</main> 
          </WatchlistProvider>
          <Footer />
      </body>
    </html>
  );
}
